### ISSUE TITLE
Declare and properly document path and query string parameters

### ISSUE THREAD

**Issue by petrbel** [iterait/apistrap#10]

**Comment by petrbel** [comment]
I think **1.** is pretty ok and probably easily implementable? In addition, defining up to three models per request seems a bit much (can be solved by **3.** as well).

Are there any drawbacks in **1.** except the lack of weird naming?

**Comment by Teyras** [comment]
The only thing I can think of now (not that it means that much :)) is that you won't be able to tell which parameter comes from the path and which comes from the query string at first glance in the request handler. This can be seen as both a benefit and a drawback though.

**Comment by Teyras** [comment]
Also, splitting the parameters into request body (current `accepts` decorator) and everything else seems kinda... arbitrary.

**Comment by Teyras** [comment]
Related to #6

**Comment by Teyras** [comment]
I'll try to outline the problems we currently need to solve and maybe suggest some solutions.

1. We need to declare path parameters and their types for AioHTTP (now we just blindly pick them from `request.match_info`, which is not nice). If we use approach 1. (a model with path and query parameters), there'll be a conflict in how path parameters are handled in Flask and AioHTTP - the former passes them as parameters to the view function, the latter will receive them in a parameter model. 
**Question**: is it OK to remove path parameters from Flask view functions decorated with `@oapi.params(SomeModel)` and replace them with a single parameter that accepts `SomeModel`?
**Alternate path**: Inject path parameters into AioHTTP view functions as parameters, just like Flask does it
2. Parameters must be documented. The Flask view functions sometimes have docblocks that describe them, but we would need to parse these (not a trivial task). If we went with the "path and query parameter model" approach, we could use the field metadata of Schematics models (like we do it for request/response models). 
**Question**: can we omit `:param:`, `:return` and other tags from the doc block if we already document this elsewhere? The view handlers probably won't be handled by Sphinx anyway.

@FloopCZ @blazekadam @petrbel @bedapisl @gdynusa

**Comment by Teyras** [comment]
**Update**: 
- Path parameters for AioHTTP are now extracted from the route and passed to function as arguments. Type of the view parameters determines the type of the path parameter. 
- Documentation is taken from the docstring
- It remains to be decided what to do with query string parameters. I suggest adding a decorator to declare them and handle them like path parameters from there.
