### ISSUE TITLE
CI tests fail (AttributeError: AssertionRewritingHook.is_package() method is missing but is required by Flask of PEP 302 import hooks.  If you do not use import hooks and you encounter this error please file a bug against Flask.)

### ISSUE THREAD

**Issue by petrbel** [iterait/apistrap#76]
It works locally, though. Maybe it will fix by itself later.

See e.g. https://circleci.com/gh/iterait/apistrap/857

**Comment by Teyras** [comment]
@petrbel I think this is not a thing anymore. If I'm right, can we close the issue?
