### ISSUE TITLE
Allow declaring multiple responses of the same type with different codes

### ISSUE THREAD

**Issue by petrbel** [iterait/apistrap#9]

**Comment by Teyras** [comment]
How will apistrap know which code to send? Will the view function be required to state it explicitly? Or should one of the codes be marked as default somehow? @petrbel

**Comment by petrbel** [comment]
I was thinking about returning a tuple instead of just the model, e.g.
```
return MyResponse(dict(a=1, b="x")), 201
```

I think flask handles this in a similar way. I guess we could force specifying the code explicitely in case there are multiple possible codes?
